# Copyright (c) 2026 C. Klukas. All rights reserved.
# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.28)
if(NOT IS_ABSOLUTE "${CKMUX_SOURCE_DIR}" OR NOT IS_ABSOLUTE "${CKMUX_PACKAGE_SCRATCH}")
    message(FATAL_ERROR "Absolute source and owned scratch paths are required")
endif()
if(NOT DEFINED CKMUX_PACKAGE_CASE)
    # Shipping must depend on both native package jobs, not only Unix builds.
    # This contract check complements, and does not replace, installed execution.
    file(READ "${CKMUX_SOURCE_DIR}/.github/workflows/release.yml" workflow)
    foreach(required IN ITEMS "windows-2025-vs2026" "windows-11-vs2026-arm"
            "needs: [package, windows-package, homebrew]" "pattern: packages-*"
            "test-package.ps1" "CKMUX_CONPTY_ARCHIVE=" "foreach($generator in @('ZIP','WIX'))")
        string(FIND "${workflow}" "${required}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "Windows release contract absent: ${required}")
        endif()
    endforeach()
    foreach(script IN ITEMS check-package package-profile-worker package-profile-host test-package)
        if(NOT EXISTS "${CKMUX_SOURCE_DIR}/tools/windows/${script}.ps1")
            message(FATAL_ERROR "Public installed-package fixture absent: ${script}")
        endif()
    endforeach()
    file(READ "${CKMUX_SOURCE_DIR}/tools/windows/check-package.ps1" checker)
    if(checker MATCHES "VersionOnly|LifecycleBrokerDirectory")
        message(FATAL_ERROR "Release package checker permits reduced lifecycle coverage")
    endif()
    string(FIND "${checker}" "Native \"$Name-lifecycle\"" invocation)
    if(invocation EQUAL -1)
        message(FATAL_ERROR "Actual installed-package lifecycle invocation absent")
    endif()
    foreach(case IN ITEMS x64 arm64 emulated inbox foreign invalid old-msi)
        execute_process(COMMAND "${CMAKE_COMMAND}"
            "-DCKMUX_SOURCE_DIR=${CKMUX_SOURCE_DIR}"
            "-DCKMUX_PACKAGE_SCRATCH=${CKMUX_PACKAGE_SCRATCH}/${case}"
            "-DCKMUX_PACKAGE_CASE=${case}" -P "${CMAKE_CURRENT_LIST_FILE}"
            RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(case STREQUAL foreign OR case STREQUAL invalid OR case STREQUAL old-msi)
            if(code EQUAL 0)
                message(FATAL_ERROR "Invalid package policy ${case} accepted")
            endif()
            if(case STREQUAL foreign AND NOT error MATCHES "only valid for a Windows target")
                message(FATAL_ERROR "Wrong foreign-platform refusal: ${error}")
            elseif(case STREQUAL invalid AND NOT error MATCHES "explicit x64 or arm64")
                message(FATAL_ERROR "Wrong architecture refusal: ${error}")
            elseif(case STREQUAL old-msi AND NOT error MATCHES "requires CMake 4.3")
                message(FATAL_ERROR "Wrong MSI prerequisite refusal: ${error}")
            endif()
        elseif(NOT code EQUAL 0)
            message(FATAL_ERROR "Windows policy ${case} failed: ${output}${error}")
        endif()
    endforeach()
    message(STATUS "Seven Windows distribution policy cases passed; not native install proof")
    return()
endif()

# Exercise the application's exact selection/call path, not binary deployment:
# ckVision owns the latter and its installed-package/native gates test it.
set(WIN32 TRUE)
set(CMAKE_VS_PLATFORM_NAME x64)
set(CKMUX_CONPTY_ARCHIVE "${CKMUX_PACKAGE_SCRATCH}/official.nupkg")
if(CKMUX_PACKAGE_CASE STREQUAL arm64)
    set(CMAKE_VS_PLATFORM_NAME ARM64)
elseif(CKMUX_PACKAGE_CASE STREQUAL emulated)
    set(CMAKE_SYSTEM_PROCESSOR ARM64)
elseif(CKMUX_PACKAGE_CASE STREQUAL inbox)
    set(CKMUX_CONPTY_ARCHIVE "")
elseif(CKMUX_PACKAGE_CASE STREQUAL foreign)
    set(WIN32 FALSE)
elseif(CKMUX_PACKAGE_CASE STREQUAL invalid)
    set(CMAKE_VS_PLATFORM_NAME Win32)
endif()
set_property(GLOBAL PROPERTY CKMUX_POLICY_CALLS 0)
function(ckvision_deploy_conpty)
    cmake_parse_arguments(PARSE_ARGV 0 deployment "" "TARGET;ARCHIVE;SHA256;ARCHITECTURE;INSTALL_DESTINATION" "")
    if(deployment_UNPARSED_ARGUMENTS OR deployment_KEYWORDS_MISSING_VALUES OR
       NOT deployment_TARGET STREQUAL ckmux OR
       NOT deployment_ARCHIVE STREQUAL CKMUX_CONPTY_ARCHIVE OR
       NOT deployment_SHA256 STREQUAL "4d6aaddc1d2385c9f5897df28f33879f699f8f2783315d5204cf3d8c3616ac5f" OR
       NOT deployment_ARCHITECTURE STREQUAL CKMUX_WINDOWS_ARCHITECTURE OR
       NOT deployment_INSTALL_DESTINATION STREQUAL "bin")
        message(FATAL_ERROR "Wrong actual library deployment invocation")
    endif()
    set_property(GLOBAL PROPERTY CKMUX_POLICY_CALLS 1)
endfunction()
include("${CKMUX_SOURCE_DIR}/cmake/WindowsRuntime.cmake")
ckmux_deploy_windows_runtime(ckmux bin)
get_property(calls GLOBAL PROPERTY CKMUX_POLICY_CALLS)
if(CKMUX_PACKAGE_CASE STREQUAL inbox)
    if(NOT calls EQUAL 0)
        message(FATAL_ERROR "Inbox-only build unexpectedly deploys a runtime")
    endif()
else()
    if(NOT calls EQUAL 1)
        message(FATAL_ERROR "Application did not invoke the library deployment helper")
    endif()
endif()
set(CMAKE_CURRENT_SOURCE_DIR "${CKMUX_SOURCE_DIR}")
set(CMAKE_CURRENT_BINARY_DIR "${CKMUX_PACKAGE_SCRATCH}")
file(READ "${CKMUX_SOURCE_DIR}/CMakeLists.txt" project_source)
string(REGEX MATCH "project\\(ckmux VERSION ([0-9.]+) " project_match "${project_source}")
if(NOT project_match)
    message(FATAL_ERROR "Cannot derive current package version")
endif()
set(PROJECT_VERSION "${CMAKE_MATCH_1}")
include("${CKMUX_SOURCE_DIR}/cmake/WindowsPackaging.cmake")
if(NOT CPACK_GENERATOR STREQUAL ZIP OR NOT CPACK_WIX_INSTALL_SCOPE STREQUAL perUser OR
   NOT CPACK_WIX_ARCHITECTURE STREQUAL CKMUX_WINDOWS_ARCHITECTURE OR
   NOT CPACK_PACKAGE_FILE_NAME STREQUAL "ckmux-${PROJECT_VERSION}-Windows-${CKMUX_WINDOWS_ARCHITECTURE}")
    message(FATAL_ERROR "Windows package identity/scope mismatch")
endif()
if(CKMUX_PACKAGE_CASE STREQUAL arm64)
    if(NOT CKMUX_WINDOWS_ARCHITECTURE STREQUAL arm64 OR NOT CPACK_WIX_UPGRADE_GUID STREQUAL "B90B17C0-BCF9-4506-B5BB-457245804F10")
        message(FATAL_ERROR "Wrong ARM64 identity")
    endif()
elseif(NOT CKMUX_WINDOWS_ARCHITECTURE STREQUAL x64 OR NOT CPACK_WIX_UPGRADE_GUID STREQUAL "63F125D8-E36D-45C4-8E12-24E8E6A2EBA8")
    message(FATAL_ERROR "Wrong x64 identity; do not infer an emulated app's ABI from its OS")
endif()
set(CPACK_GENERATOR WIX)
set(CMAKE_VERSION 4.3)
if(CKMUX_PACKAGE_CASE STREQUAL old-msi)
    set(CMAKE_VERSION 4.2)
endif()
include("${CPACK_PROJECT_CONFIG_FILE}")
