# Copyright (c) 2026 C. Klukas. All rights reserved.
# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.28)

if(NOT IS_ABSOLUTE "${CKMUX_SOURCE_DIR}" OR NOT IS_ABSOLUTE "${CKMUX_PIN_SCRATCH}")
    message(FATAL_ERROR "Explicit absolute source and scratch paths are required")
endif()
file(READ "${CKMUX_SOURCE_DIR}/CMakeLists.txt" source)
string(REGEX MATCH "set\\(CKMUX_CKVISION_VERSION ([0-9.]+)\\)" pin_declaration "${source}")
set(pin "${CMAKE_MATCH_1}")
if(pin STREQUAL "")
    message(FATAL_ERROR "No release pin found")
endif()
# Exercise the real declaration's arguments, not a second policy written in
# this test. Removing EXACT must make the later-version case fail.
string(REGEX MATCH "\n[ \t]+FIND_PACKAGE_ARGS ([^)]*)\\)" find_declaration "${source}")
set(arguments "${CMAKE_MATCH_1}")
if(arguments STREQUAL "")
    message(FATAL_ERROR "No installed-package lookup arguments found")
endif()
string(REPLACE "\${CKMUX_CKVISION_VERSION}" "${pin}" arguments "${arguments}")
separate_arguments(arguments UNIX_COMMAND "${arguments}")

include(CMakePackageConfigHelpers)
string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$" components "${pin}")
set(major "${CMAKE_MATCH_1}")
set(minor "${CMAKE_MATCH_2}")
set(patch "${CMAKE_MATCH_3}")
math(EXPR future_patch "${patch} + 1")
if(patch GREATER 0)
    math(EXPR older_patch "${patch} - 1")
    set(older_version "${major}.${minor}.${older_patch}")
elseif(minor GREATER 0)
    math(EXPR older_minor "${minor} - 1")
    set(older_version "${major}.${older_minor}.0")
elseif(major GREATER 0)
    math(EXPR older_major "${major} - 1")
    set(older_version "${older_major}.0.0")
else()
    message(FATAL_ERROR "The fixture needs a release newer than 0.0.0")
endif()

foreach(case IN ITEMS exact older future)
    if(case STREQUAL exact)
        set(version "${pin}")
    elseif(case STREQUAL older)
        set(version "${older_version}")
    else()
        set(version "${major}.${minor}.${future_patch}")
    endif()
    set(prefix "${CKMUX_PIN_SCRATCH}/${case}")
    file(MAKE_DIRECTORY "${prefix}")
    file(WRITE "${prefix}/ckvisionConfig.cmake" "set(CKMUX_SELECTED_FIXTURE_VERSION ${version})\n")
    write_basic_package_version_file("${prefix}/ckvisionConfigVersion.cmake"
        VERSION "${version}" COMPATIBILITY SameMajorVersion ARCH_INDEPENDENT)
    unset(ckvision_DIR)
    unset(ckvision_DIR CACHE)
    unset(CKMUX_SELECTED_FIXTURE_VERSION)
    find_package(ckvision ${arguments} QUIET NO_DEFAULT_PATH PATHS "${prefix}")
    if(case STREQUAL exact)
        if(NOT ckvision_FOUND OR NOT CKMUX_SELECTED_FIXTURE_VERSION STREQUAL pin)
            message(FATAL_ERROR "The matching installed release was not selected")
        endif()
    elseif(ckvision_FOUND OR DEFINED CKMUX_SELECTED_FIXTURE_VERSION)
        message(FATAL_ERROR "The ${case} installed release ${version} bypassed pin ${pin}")
    endif()
endforeach()
message(STATUS "Installed release selection accepts only ${pin}")
